serene/auths/urls.py
from django.urls import path, include
from .views import organizer_dashboard

urlpatterns = [
    path('', include('allauth.urls')),
    path('organizer-dashboard/', organizer_dashboard, name='organizer_dashboard'),
]

serene/events/urls.py
from django.urls import path
from . import views
app_name = "events"

urlpatterns = [
    # events url
    path('', views.events, name="events"),
    # all events
    path('all-events/', views.all_events, name="all-events"),
    # search events url
    path('search/', views.search_events, name='search_events'),
    #  event Detail
    path('online-event/<int:pk>/', views.online_event, name='online_event_detail'),
    path('venue-event/<int:pk>/', views.venue_event, name='venue_event_detail'),
    # booking url
    path('book_event/<int:event_id>/<str:event_type>/', views.book_event, name="book_event"),
    # booking Confirmed url
    path('booking_confirmation/', views.booking_confirmation, name="booking_confirmation"),
    # create
    path('create/', views.create, name="create"),
    # create online event url
    path('create-online-event/', views.create_online_event, name="create-online-event"),
    # create venue event url
    path('create-venue-event/', views.create_venue_event, name="create-venue-event"),
]

serene/serene/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('auths.urls')),
    path('', include('events.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

serene/templates/venue_event.html
{% extends "includes/base.html" %}
{% load static %}
{% load custom_filters %}
{% block content %}
<div class="breadcrumb-block">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 col-md-10">
				<div class="barren-breadcrumb">
					<nav aria-label="breadcrumb">
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="index.html">Home</a></li>
							<li class="breadcrumb-item"><a href="all-events.html">Explore Events</a></li>
							<li class="breadcrumb-item active" aria-current="page">Venue Event Detail View</li>
						</ol>
					</nav>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="event-dt-block p-80">
    <div class="container">
        <div class="row">
            <div class="col-xl-12 col-lg-12 col-md-12">
                <div class="event-top-dts">
                    <div class="event-top-date">
                        <span class="event-month">{{ event.event_date | date:"M" }}</span>
                        <span class="event-date">{{ event.event_date | date:"d" }}</span>
                    </div>
                    <div class="event-top-dt">
                        <h3 class="event-main-title">{{ event.event_name }}</h3>
                        <div class="event-top-info-status">
                            <span class="event-type-name"><i class="fa-solid fa-location-dot"></i>Venue Event</span>
                            <span class="event-type-name details-hr">Starts on <span class="ev-event-date">{{ event.event_date | date:"D, M d, Y h:i A" }}</span></span>
                            <span class="event-type-name details-hr">{{ event.event_duration|format_duration }}</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-8 col-lg-7 col-md-12">
                <div class="main-event-dt">
                    <div class="event-img">
                        <img src="{% static event.event_image.url %}" alt="{{ event.title }}">
                    </div>
                    <div class="share-save-btns dropdown">
                        <button class="sv-btn me-2"><i class="fa-regular fa-bookmark me-2"></i>Save</button>
                        <button class="sv-btn" data-bs-toggle="dropdown" aria-expanded="false"><i class="fa-solid fa-share-nodes me-2"></i>Share</button>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#"><i class="fa-brands fa-facebook me-3"></i>Facebook</a></li>
                            <li><a class="dropdown-item" href="#"><i class="fa-brands fa-twitter me-3"></i>Twitter</a></li>
                            <li><a class="dropdown-item" href="#"><i class="fa-brands fa-linkedin-in me-3"></i>LinkedIn</a></li>
                            <li><a class="dropdown-item" href="#"><i class="fa-regular fa-envelope me-3"></i>Email</a></li>
                        </ul>
                    </div>
                    <div class="main-event-content">
                        <h4>About This Event</h4>
                        <p>{{ event.event_description|linebreaks }}</p>
                    </div>
                </div>
            </div>
            <div class="col-xl-4 col-lg-5 col-md-12">
                <div class="main-card event-right-dt">
                    <div class="bp-title">
                        <h4>Event Details</h4>
                    </div>
                    <div class="time-left">
                        <div class="countdown" id="countdown">
                            <div class="countdown-item">
                                <span id="day"></span>days
                            </div>
                            <div class="countdown-item">
                                <span id="hour"></span>Hours
                            </div>
                            <div class="countdown-item">
                                <span id="minute"></span>Minutes
                            </div>
                            <div class="countdown-item">
                                <span id="second"></span>Seconds
                            </div>
                        </div>
                    </div>
                    <div class="event-dt-right-group mt-5">
                        <div class="event-dt-right-icon">
                            <i class="fa-solid fa-circle-user"></i>
                        </div>
                        <div class="event-dt-right-content">
                            <h4>Organised by</h4>
                            <h5>{{ event.organizer_name }}</h5>
							<a href="#">View Profile</a>
                            <!-- <a href="#">View Profile</a> -->
                        </div>
                    </div>
                    <div class="event-dt-right-group">
                        <div class="event-dt-right-icon">
                            <i class="fa-solid fa-calendar-day"></i>
                        </div>
                        <div class="event-dt-right-content">
                            <h4>Date and Time</h4>
                            <h5>{{ event.event_date | date:"D, M d, Y h:i A" }}</h5>
                            <div class="add-to-calendar">
                                <a href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="fa-regular fa-calendar-days me-3"></i>Add to Calendar
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="#"><i class="fa-brands fa-windows me-3"></i>Outlook</a></li>
                                    <li><a class="dropdown-item" href="#"><i class="fa-brands fa-apple me-3"></i>Apple</a></li>
                                    <li><a class="dropdown-item" href="#"><i class="fa-brands fa-google me-3"></i>Google</a></li>
                                    <li><a class="dropdown-item" href="#"><i class="fa-brands fa-yahoo me-3"></i>Yahoo</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="event-dt-right-group">
                        <div class="event-dt-right-icon">
                            <i class="fa-solid fa-location-dot"></i>
                        </div>
                        <div class="event-dt-right-content">
                            <h4>Location</h4>
                            <h5 class="mb-0">{{ event.event_location }}</h5>
                            <a href="#"><i class="fa-solid fa-location-dot me-2"></i>View Map</a>
                        </div>
                    </div>
                    <div class="select-tickets-block">
                        <h6>Select Tickets</h6>
                        <div class="select-ticket-action">
                            <div class="ticket-price">{{ event.ticket_price }}</div>
                            <div class="quantity">
                                <div class="counter">
                                    <span class="down" onClick='decreaseCount(event, this)'>-</span>
                                    <input type="text" value="0">
                                    <span class="up" onClick='increaseCount(event, this)'>+</span>
                                </div>
                            </div>
                        </div>
                        <p>{{ event.ticket_details }}</p>
                        <div class="xtotel-tickets-count">
                            <div class="x-title">1x Ticket(s)</div>
                            <h4>{{ event.ticket_price }}</h4>
                        </div>
                    </div>
                    <div class="booking-btn">
                        {% if event_already_booked %}
                            <span class="main-btn btn-hover w-100 disabled">Already Booked</span>
                        {% else %}
                            <a href="{% url 'events:book_event' event_type='venue' event_id=event.id %}" class="main-btn btn-hover w-100">Book Now</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-xl-12 col-lg-12 col-md-12">
                <div class="more-events">
                    <div class="main-title position-relative">
                        <h3>More Events</h3>
                        <a href="{% url 'events:all-events' %}" class="view-all-link">Browse All<i class="fa-solid fa-right-long ms-2"></i></a>
                    </div>
                    <div class="owl-carousel moreEvents-slider owl-theme">
                        {% for more_event in more_events %}
                        <div class="item">
                            <div class="main-card mt-4">
                                <div class="event-thumbnail">
                                    <a href="{% url 'events:venue_event_detail' more_event.id %}" class="thumbnail-img">
                                        <img src="{% static more_event.event_image.url %}" alt="{{ more_event.event_name }}">
                                    </a>
                                    <span class="bookmark-icon" title="Bookmark"></span>
                                </div>
                                <div class="event-content">
                                    <a href="{% url 'events:venue_event_detail' more_event.id %}" class="event-title">{{ more_event.event_name }}</a>
                                    <div class="duration-price-remaining">
                                        <span class="duration-price">{{ more_event.price }}Free*</span>
                                        <span class="remaining">{{ more_event.remaining_tickets }}2 Tickets Remaining</span>
                                        <span id="eventStartDate" style="display: none;">{{ event.event_date|date:"Y-m-d H:i:s" }}</span>
                                    </div>
                                </div>
                                <div class="event-footer">
                                    <div class="event-timing">
                                        <div class="publish-date">
                                            <span><i class="fa-solid fa-calendar-day me-2"></i>{{ more_event.event_date | date:"d M" }}</span>
                                            <span class="dot"><i class="fa-solid fa-circle"></i></span>
                                            <span>{{ more_event.event_time}}</span>
                                        </div>
                                        <span class="publish-time"><i class="fa-solid fa-clock me-2"></i>{{ more_event.event_duration|format_duration }}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
    // Get the event start date from the hidden element
    var eventStartDateStr = document.getElementById('eventStartDate').textContent;
    var eventStartDate = new Date(eventStartDateStr).getTime();
    var eventEndDate = eventStartDate + 24 * 60 * 60 * 1000; // Add 24 hours to the start date

    // Select the button element
    var bookingBtn = document.querySelector('.booking-btn .main-btn');

    // Update the countdown every 1 second
    var x = setInterval(function() {
        // Get the current date and time
        var now = new Date().getTime();

        // Calculate the distance between now and the event start date
        var distanceToStart = eventStartDate - now;
        var distanceToEnd = eventEndDate - now;

        // Calculate days, hours, minutes, and seconds
        var days = Math.floor(distanceToStart / (1000 * 60 * 60 * 24));
        var hours = Math.floor((distanceToStart % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
        var minutes = Math.floor((distanceToStart % (1000 * 60 * 60)) / (1000 * 60));
        var seconds = Math.floor((distanceToStart % (1000 * 60)) / 1000);

        // Display the countdown
        document.getElementById("day").innerHTML = days;
        document.getElementById("hour").innerHTML = hours;
        document.getElementById("minute").innerHTML = minutes;
        document.getElementById("second").innerHTML = seconds;

        // If the event has started but not ended, display "Event has started."
        if (distanceToStart < 0 && distanceToEnd >= 0) {
            document.getElementById("countdown").innerHTML = "Event Has Started.";
            bookingBtn.innerHTML = "Join";
            bookingBtn.classList.remove('disabled');
            bookingBtn.setAttribute('href', '#');
        } 
        // If the event has ended, display "Event ended."
        else if (distanceToEnd < 0) {
            bookingBtn.innerHTML = "Ended";
            bookingBtn.classList.add('disabled');
            bookingBtn.removeAttribute('href');
            clearInterval(x);
            document.getElementById("countdown").innerHTML = "Event Has Ended.";
        }
    }, 1000); // Update every 1 second
});
</script>

{% endblock content %}