serene/auths/urls.py
from django.urls import path, include
from .views import organizer_dashboard

urlpatterns = [
    path('', include('allauth.urls')),
    path('organizer-dashboard/', organizer_dashboard, name='organizer_dashboard'),
]

serene/events/urls.py
from django.urls import path
from . import views
app_name = "events"

urlpatterns = [
    # events url
    path('', views.events, name="events"),
    # all events
    path('all-events/', views.all_events, name="all-events"),
    # search events url
    path('search/', views.search_events, name='search_events'),
    #  event Detail
    path('online-event/<int:pk>/', views.online_event, name='online_event_detail'),
    path('venue-event/<int:pk>/', views.venue_event, name='venue_event_detail'),
    # booking url
    path('book_event/<int:event_id>/<str:event_type>/', views.book_event, name="book_event"),
    # booking Confirmed url
    path('booking_confirmation/', views.booking_confirmation, name="booking_confirmation"),
    # create
    path('create/', views.create, name="create"),
    # create online event url
    path('create-online-event/', views.create_online_event, name="create-online-event"),
    # create venue event url
    path('create-venue-event/', views.create_venue_event, name="create-venue-event"),
]

serene/serene/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('auths.urls')),
    path('', include('events.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

serene/templates/includes/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, shrink-to-fit=9">
	<meta name="description">
	<meta name="author">
	<title>Serene - Blooms</title>

	<!-- Favicon Icon -->
	<link rel="icon" type="image/png" href="{% static 'images/fav.png' %}">

	<!-- Stylesheets -->
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link
		href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
		rel="stylesheet">
	<link href="{% static 'vendor/unicons-2.0.1/css/unicons.css' %}" rel='stylesheet'>
	<link href="{% static 'css/style.css' %}" rel="stylesheet">
	<link href="{% static 'css/responsive.css' %}" rel="stylesheet">
	<link href="{% static 'css/night-mode.css' %}" rel="stylesheet">

	<!-- Vendor Stylesheets -->
	<link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
	<link href="{% static 'vendor/OwlCarousel/assets/owl.carousel.css' %}" rel="stylesheet">
	<link href="{% static 'vendor/OwlCarousel/assets/owl.theme.default.min.css' %}" rel="stylesheet">
	<link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'vendor/bootstrap-select/dist/css/bootstrap-select.min.css' %}" rel="stylesheet">
	<link href="{% static 'css/datepicker.min.css' %}" rel="stylesheet">
	<link href="{% static 'css/jquery-steps.css' %}" rel="stylesheet">	
	<link href="{% static 'vendor/ckeditor5/sample/css/sample.css' %}" rel="stylesheet">	

</head>

<body class="d-flex flex-column h-100">
	<style>
        /* Center the messages */
        .messages {
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
        }

        /* Style for individual message */
        .alert {
            margin: 10px;
            padding: 10px;
            border-radius: 5px;
        }

        /* Additional classes for different alert types */
        .alert-success {
            background-color: #d4edda;
            color: green;
        }
        .alert-error {
            background-color: #f8d7da;
            color: red;
        }
        .alert-info {
            background-color: #cce5ff;
            color: blue;
        }
        .alert-warning {
            background-color: #fff3cd;
            color: orange;
        }
    </style>
	<!-- Header Start-->
	<header class="header">
		<div class="header-inner">
			<nav
				class="navbar navbar-expand-lg bg-barren barren-head navbar fixed-top justify-content-sm-start pt-0 pb-0">
				<div class="container">
					<button class="navbar-toggler" type="button" data-bs-toggle="offcanvas"
						data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
						<span class="navbar-toggler-icon">
							<i class="fa-solid fa-bars"></i>
						</span>
					</button>
					<a class="navbar-brand order-1 order-lg-0 ml-lg-0 ml-2 me-auto" href="#">
						<div class="res-main-logo">
							<img src="{% static 'images/logo-icon.svg' %}" alt="">
						</div>
						<div class="main-logo" id="logo">
							<img src="{% static 'images/logo.svg' %}" alt="">
							<img class="logo-inverse" src="{% static 'images/dark-logo.svg' %}" alt="">
						</div>
					</a>
					<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar"
						aria-labelledby="offcanvasNavbarLabel">
						<div class="offcanvas-header">
							<div class="offcanvas-logo" id="offcanvasNavbarLabel">
								<img src="{% static 'images/logo-icon.svg' %}" alt="">
							</div>
							<button type="button" class="close-btn" data-bs-dismiss="offcanvas" aria-label="Close">
								<i class="fa-solid fa-xmark"></i>
							</button>
						</div>
						<div class="offcanvas-body">
							{% if request.user.is_organizer %}
							<div class="offcanvas-top-area">
								<div class="create-bg">
									<a href="#" class="offcanvas-create-btn">
										<i class="fa-solid fa-calendar-days"></i>
										<span>Create Event</span>
									</a>
								</div>
							</div>
							{% else %}
							<div class="offcanvas-top-area">
								<div class="create-bg">
                                    <a href="#" class="offcanvas-create-btn">
                                        <i class="fa-solid fa-calendar-days"></i>
                                        <span>Search Events</span>
                                    </a>
                                </div>
							</div>
							{% endif %}
							<ul class="navbar-nav justify-content-end flex-grow-1 pe-5">
								<li class="nav-item">
									<a class="nav-link {% if request.path == home_url %}active{% endif %}" aria-current="page" href="{% url 'events:events' %}">Home</a>
								</li>
								<li class="nav-item">
									<a class="nav-link {% if request.path == explore_url %}active{% endif %}" href="{% url 'events:all-events' %}" role="button" aria-expanded="false">
										Explore Events
									</a>
								</li>
							</ul>
						</div>
						<div class="offcanvas-footer">
							<div class="offcanvas-social">
								<h5>Follow Us</h5>
								<ul class="social-links">
									<li><a href="#" class="social-link"><i class="fab fa-facebook-square"></i></a>
									<li><a href="#" class="social-link"><i class="fab fa-instagram"></i></a>
									<li><a href="#" class="social-link"><i class="fab fa-twitter"></i></a>
									<li><a href="#" class="social-link"><i class="fab fa-linkedin-in"></i></a>
									<li><a href="#" class="social-link"><i class="fab fa-youtube"></i></a>
								</ul>
							</div>
						</div>
					</div>
					<div class="right-header order-2">
						<ul class="align-self-stretch">
							{% if request.user.is_organizer %}
							<li>
								<a href="{% url 'events:create' %}" class="create-btn btn-hover">
									<i class="fa-solid fa-calendar-days"></i>
									<span>Create Event</span>
								</a>
							</li>
							{% endif %}
							<li class="dropdown account-dropdown">
								<a href="#" class="account-link" role="button" id="accountClick"
									data-bs-auto-close="outside" data-bs-toggle="dropdown" aria-expanded="false">
									<img src="{% static 'images/profile-imgs/img-13.jpg' %}" alt="">
									<i class="fas fa-caret-down arrow-icon"></i>
								</a>
								<ul class="dropdown-menu dropdown-menu-account dropdown-menu-end"
									aria-labelledby="accountClick">
									<li>
										<div class="dropdown-account-header">
											<div class="account-holder-avatar">
												<img src="{% static 'images/profile-imgs/img-13.jpg' %}" alt="">
											</div>
											<p>{{request.user.email|capfirst}}</p>
										</div>
									</li>
									<li class="profile-link">
										<a href="{% url 'organizer_dashboard' %}" class="link-item">My Organisation</a>
										<a href="#" class="link-item">My Profile</a>
										{% if request.user.is_authenticated %}
										<a href="{% url 'account_logout' %}" class="link-item">Sign Out</a>
										{% else %}
										<a href="{% url 'account_login' %}" class="link-item">Sign In</a>
										{% endif %}

									</li>
								</ul>
							</li>
							<li>
								<div class="night_mode_switch__btn">
									<div id="night-mode" class="fas fa-moon fa-sun"></div>
								</div>
							</li>
						</ul>
					</div>
				</div>
			</nav>
			<div class="overlay"></div>
		</div>
	</header>
	<!-- Header End-->
	<!-- Body Start-->
	<div class="wrapper">
		<!-- Messages Div -->
		{% if messages %}
		<div id="messages" class="messages">
			{% for message in messages %}
			<div class="alert alert-{{ message.tags }}">
				{{ message }}
			</div>
			{% endfor %}
		</div>
		{% endif %}

		{% block content %}

		{% endblock content %}
	</div>
	<!-- Body End-->
	<!-- Footer Start-->
	<footer class="footer mt-auto">
		<div class="footer-top">
			<div class="container">
				<div class="row">
					<div class="col-lg-3 col-md-6">
						<div class="footer-content">
							<h4>Company</h4>
							<ul class="footer-link-list">
								<li><a href="#" class="footer-link">About Us</a></li>
								<li><a href="#" class="footer-link">Help Center</a></li>
								<li><a href="#" class="footer-link">FAQ</a></li>
								<li><a href="#" class="footer-link">Contact Us</a></li>
							</ul>
						</div>
					</div>
					<div class="col-lg-3 col-md-6">
						<div class="footer-content">
							<h4>Resources</h4>
							<ul class="footer-link-list">
								<li><a href="" class="footer-link">Pricing</a></li>
							</ul>
						</div>
					</div>
					<div class="col-lg-3 col-md-6">
						<div class="footer-content">
							<h4>Follow Us</h4>
							<ul class="social-links">
								<li><a href="#" class="social-link"><i class="fab fa-facebook-square"></i></a>
								<li><a href="#" class="social-link"><i class="fab fa-instagram"></i></a>
								<li><a href="#" class="social-link"><i class="fab fa-twitter"></i></a>
								<li><a href="#" class="social-link"><i class="fab fa-linkedin-in"></i></a>
								<li><a href="#" class="social-link"><i class="fab fa-youtube"></i></a>
							</ul>
						</div>
						<!-- <div class="footer-content">
							<h4>Download Mobile App</h4>
							<div class="download-app-link">
								<a href="#" class="download-btn"><img src="{% static 'images/app-store.png' %}"
										alt=""></a>
								<a href="#" class="download-btn"><img src="{% static 'images/google-play.png' %}"
										alt=""></a>
							</div>
						</div> -->
					</div>
				</div>
			</div>
		</div>
		<div class="footer-bottom">
			<div class="container">
				<div class="row">
					<div class="col-12">
						<div class="footer-copyright-text">
							<p class="mb-0">© 2024, <strong>Serene</strong>. All rights reserved.</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</footer>
	<!-- Footer End-->

	<script>
		// Auto-dismiss messages after 5 seconds
		setTimeout(function() {
			var messagesDiv = document.getElementById('messages');
			if (messagesDiv) {
				messagesDiv.style.transition = 'opacity 1s';
				messagesDiv.style.opacity = '0';
				setTimeout(function() {
					messagesDiv.style.display = 'none';
				}, 1000);
			}
		}, 5000);
	</script>
	<script src="https://unpkg.com/imask"></script>
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
	<script src="{% static 'vendor/OwlCarousel/owl.carousel.js' %}"></script>
	<script src="{% static 'vendor/bootstrap-select/dist/js/bootstrap-select.min.js' %}"></script>
	<script src="{% static 'vendor/mixitup/dist/mixitup.min.js' %}"></script>
	<script src="{% static 'js/custom.js' %}"></script>
	<script src="{% static 'js/night-mode.js' %}"></script>
	<script src="{% static 'vendor/ckeditor5/ckeditor.js' %}"></script>
	<script src="{% static 'js/jquery-steps.min.js' %}"></script>
	<script src="{% static 'js/datepicker.min.js' %}"></script>
	<script src="{% static 'js/i18n/datepicker.en.js' %}"></script>
	<script>
		var containerEl = document.querySelector('[data-ref~="event-filter-content"]');

		var mixer = mixitup(containerEl, {
			selectors: {
				target: '[data-ref~="mixitup-target"]'
			}
		});
	</script>
</body>

</html>